from string_to_aiger.logic.circuit import BoolConst, InputVar, And, Or, Expr
from .sequential_circuit import SequentialCircuit


class SequentialAigerWriter:
    """Serialize a SequentialCircuit into ASCII AIGER with latches."""

    def __init__(self, circuit: SequentialCircuit):
        self.circuit = circuit

        self.input_literals: dict[str, int] = {}
        self.latch_literals: dict[str, int] = {}
        self.and_literals: list[tuple[int, int, int]] = []

        self.next_var = 1

    def new_literal(self) -> int:
        lit = 2 * self.next_var
        self.next_var += 1
        return lit

    def invert(self, lit: int) -> int:
        return lit ^ 1

    def setup_inputs_and_latches(self) -> None:
        for name in sorted(self.circuit.inputs):
            self.input_literals[name] = self.new_literal()

        for name in self.circuit.latches:
            self.latch_literals[name] = self.new_literal()

    def new_and(self, left_lit: int, right_lit: int) -> int:
        out_lit = self.new_literal()
        self.and_literals.append((out_lit, left_lit, right_lit))
        return out_lit

    def compile_expr(self, expr: Expr) -> int:
        if isinstance(expr, BoolConst):
            return 1 if expr.value else 0

        if isinstance(expr, InputVar):
            if expr.name in self.input_literals:
                return self.input_literals[expr.name]

            if expr.name in self.latch_literals:
                return self.latch_literals[expr.name]

            raise ValueError(f"Unknown input/latch variable: {expr.name}")

        if isinstance(expr, And):
            left_lit = self.compile_expr(expr.left)
            right_lit = self.compile_expr(expr.right)
            return self.new_and(left_lit, right_lit)

        if isinstance(expr, Or):
            left_lit = self.compile_expr(expr.left)
            right_lit = self.compile_expr(expr.right)

            # a OR b = ~(~a AND ~b)
            and_lit = self.new_and(
                self.invert(left_lit),
                self.invert(right_lit),
            )
            return self.invert(and_lit)

        raise TypeError(
            f"Unsupported expression in sequential AIGER writer: {type(expr)}"
        )

    def write(self) -> str:
        self.setup_inputs_and_latches()

        latch_next_literals: dict[str, int] = {}
        for name, latch in self.circuit.latches.items():
            latch_next_literals[name] = self.compile_expr(latch.next_expr)

        output_literals: dict[str, int] = {}
        for name, expr in self.circuit.outputs.items():
            output_literals[name] = self.compile_expr(expr)

        num_inputs = len(self.input_literals)
        num_latches = len(self.latch_literals)
        num_outputs = len(output_literals)
        num_ands = len(self.and_literals)
        max_variable_index = self.next_var - 1

        lines = [
            f"aag {max_variable_index} {num_inputs} "
            f"{num_latches} {num_outputs} {num_ands}"
        ]

        # Inputs
        for name in sorted(self.circuit.inputs):
            lines.append(str(self.input_literals[name]))

        # Latches
        for name, latch in self.circuit.latches.items():
            current_lit = self.latch_literals[name]
            next_lit = latch_next_literals[name]
            reset_lit = 1 if latch.init else 0

            lines.append(f"{current_lit} {next_lit} {reset_lit}")

        # Outputs
        for name in output_literals:
            lines.append(str(output_literals[name]))

        # AND gates
        for lhs, rhs0, rhs1 in self.and_literals:
            lines.append(f"{lhs} {rhs0} {rhs1}")

        # Symbolic input names
        for index, name in enumerate(sorted(self.circuit.inputs)):
            lines.append(f"i{index} {name}")

        # Symbolic latch names
        for index, name in enumerate(self.circuit.latches):
            lines.append(f"l{index} {name}")

        # Symbolic output names
        for index, name in enumerate(output_literals):
            lines.append(f"o{index} {name}")

        lines.append("c")
        lines.append("generated by string-to-aiger sequential backend")

        return "\n".join(lines)
