from regex_parser import parse_regex
from regex_pretty import pretty_regex
from nfa_builder import build_nfa
from nfa_evaluator import accepts
from bounded_nfa_encoding import compile_nfa_bounded
from evaluator import evaluate
from regex_to_aiger import compile_regex_to_aiger


def test_regex_parser_basic():
    ast = parse_regex("a")
    assert pretty_regex(ast) == "a"


def test_regex_parser_concat():
    ast = parse_regex("ab")
    assert pretty_regex(ast) == "(ab)"


def test_regex_parser_union():
    ast = parse_regex("a|b")
    assert pretty_regex(ast) == "(a | b)"


def test_regex_parser_star():
    ast = parse_regex("a*")
    assert pretty_regex(ast) == "(a)*"


def test_nfa_accepts_star():
    ast = parse_regex("a*")
    nfa = build_nfa(ast)

    assert accepts(nfa, "") is True
    assert accepts(nfa, "a") is True
    assert accepts(nfa, "aa") is True
    assert accepts(nfa, "aaa") is True
    assert accepts(nfa, "b") is False
    assert accepts(nfa, "ab") is False


def test_nfa_accepts_ab_star():
    ast = parse_regex("(ab)*")
    nfa = build_nfa(ast)

    assert accepts(nfa, "") is True
    assert accepts(nfa, "ab") is True
    assert accepts(nfa, "abab") is True
    assert accepts(nfa, "a") is False
    assert accepts(nfa, "abb") is False
    assert accepts(nfa, "aba") is False


def test_bounded_encoding_a_star():
    ast = parse_regex("a*")
    nfa = build_nfa(ast)
    expr = compile_nfa_bounded(nfa, bound=3)

    assert evaluate(expr, "") is True
    assert evaluate(expr, "a") is True
    assert evaluate(expr, "aa") is True
    assert evaluate(expr, "aaa") is True

    # Rejected because the bound is 3.
    assert evaluate(expr, "aaaa") is False

    assert evaluate(expr, "b") is False
    assert evaluate(expr, "ab") is False


def test_bounded_encoding_ab_star():
    ast = parse_regex("(ab)*")
    nfa = build_nfa(ast)
    expr = compile_nfa_bounded(nfa, bound=6)

    assert evaluate(expr, "") is True
    assert evaluate(expr, "ab") is True
    assert evaluate(expr, "abab") is True
    assert evaluate(expr, "ababab") is True

    assert evaluate(expr, "a") is False
    assert evaluate(expr, "abb") is False
    assert evaluate(expr, "aba") is False
    assert evaluate(expr, "abababa") is False


def test_regex_to_aiger_output():
    aiger_text = compile_regex_to_aiger("a*", bound=3)

    assert aiger_text.startswith("aag ")
    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger" in aiger_text


def run_tests():
    test_regex_parser_basic()
    test_regex_parser_concat()
    test_regex_parser_union()
    test_regex_parser_star()
    test_nfa_accepts_star()
    test_nfa_accepts_ab_star()
    test_bounded_encoding_a_star()
    test_bounded_encoding_ab_star()
    test_regex_to_aiger_output()

    print("All regex tests passed.")


if __name__ == "__main__":
    run_tests()