import os
import subprocess
import sys
import tempfile


ROOT_DIR = os.path.dirname(os.path.dirname(__file__))
OUTPUT_DIR = os.path.join(ROOT_DIR, "outputs")


def run_cli(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "string_to_aiger"] + args,
        cwd=ROOT_DIR,
        text=True,
        capture_output=True,
    )


def test_cli_bounded_backend():
    output_path = os.path.join(OUTPUT_DIR, "test_cli_bounded.aag")

    result = run_cli([
        "--pattern", "(a|b)*&a*",
        "--backend", "bounded",
        "--bound", "4",
        "--output", output_path,
    ])

    assert result.returncode == 0
    assert os.path.exists(output_path)

    with open(output_path, "r", encoding="utf-8") as f:
        aiger_text = f.read()

    assert aiger_text.startswith("aag ")
    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger" in aiger_text


def test_cli_sequential_backend():
    output_path = os.path.join(OUTPUT_DIR, "test_cli_sequential.aag")

    result = run_cli([
        "--pattern", "(a|b)*&a*",
        "--backend", "sequential",
        "--output", output_path,
    ])

    assert result.returncode == 0
    assert os.path.exists(output_path)

    with open(output_path, "r", encoding="utf-8") as f:
        aiger_text = f.read()

    assert aiger_text.startswith("aag ")
    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger sequential backend" in aiger_text

    header = aiger_text.splitlines()[0]
    parts = header.split()

    assert parts[0] == "aag"

    num_latches = int(parts[3])
    assert num_latches > 0


def test_cli_input_file_backend():
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "pattern.txt")
        output_path = os.path.join(temp_dir, "from_file.aag")

        with open(input_path, "w", encoding="utf-8") as f:
            f.write("(a|b)*&a*")

        result = run_cli([
            "--input-file", input_path,
            "--backend", "bounded",
            "--bound", "4",
            "--output", output_path,
        ])

        assert result.returncode == 0
        assert os.path.exists(output_path)

        with open(output_path, "r", encoding="utf-8") as f:
            aiger_text = f.read()

        assert aiger_text.startswith("aag ")
        assert "o0 accept" in aiger_text
        assert "generated by string-to-aiger" in aiger_text


def test_cli_rejects_empty_input_file():
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "empty.txt")
        output_path = os.path.join(temp_dir, "empty.aag")

        with open(input_path, "w", encoding="utf-8") as f:
            f.write("")

        result = run_cli([
            "--input-file", input_path,
            "--backend", "bounded",
            "--bound", "4",
            "--output", output_path,
        ])

        assert result.returncode != 0
        assert "Input file is empty" in result.stderr


def test_cli_requires_pattern_or_input_file():
    result = run_cli([])

    assert result.returncode != 0
    assert "one of the arguments --pattern --input-file is required" in result.stderr


def test_cli_rejects_pattern_and_input_file_together():
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "pattern.txt")

        with open(input_path, "w", encoding="utf-8") as f:
            f.write("a*")

        result = run_cli([
            "--pattern", "a*",
            "--input-file", input_path,
            "--backend", "bounded",
        ])

        assert result.returncode != 0
        assert "not allowed with argument" in result.stderr


def run_tests():
    test_cli_bounded_backend()
    test_cli_sequential_backend()
    test_cli_input_file_backend()
    test_cli_rejects_empty_input_file()
    test_cli_requires_pattern_or_input_file()
    test_cli_rejects_pattern_and_input_file_together()

    print("All CLI tests passed.")


if __name__ == "__main__":
    run_tests()
