# tests_intersection.py

from regex_bounded_compiler import compile_regex_bounded
from evaluator import evaluate
from aiger import compile_expr_to_aiger


def test_intersection_a_or_b_star_and_a_star():
    expr = compile_regex_bounded("(a|b)*&a*", bound=4)

    assert evaluate(expr, "") is True
    assert evaluate(expr, "a") is True
    assert evaluate(expr, "aa") is True
    assert evaluate(expr, "aaa") is True
    assert evaluate(expr, "aaaa") is True

    assert evaluate(expr, "b") is False
    assert evaluate(expr, "ab") is False
    assert evaluate(expr, "ba") is False

    # Rejected because bound is 4.
    assert evaluate(expr, "aaaaa") is False


def test_intersection_ab_star_and_a_or_b_star():
    expr = compile_regex_bounded("(ab)*&(a|b)*", bound=6)

    assert evaluate(expr, "") is True
    assert evaluate(expr, "ab") is True
    assert evaluate(expr, "abab") is True
    assert evaluate(expr, "ababab") is True

    assert evaluate(expr, "a") is False
    assert evaluate(expr, "b") is False
    assert evaluate(expr, "aba") is False
    assert evaluate(expr, "abb") is False


def test_intersection_disjoint_languages():
    expr = compile_regex_bounded("a*&b*", bound=4)

    # Both a* and b* accept the empty string.
    assert evaluate(expr, "") is True

    # Non-empty strings cannot be both only-a and only-b.
    assert evaluate(expr, "a") is False
    assert evaluate(expr, "aa") is False
    assert evaluate(expr, "b") is False
    assert evaluate(expr, "bb") is False
    assert evaluate(expr, "ab") is False


def test_intersection_to_aiger_output():
    expr = compile_regex_bounded("(a|b)*&a*", bound=4)
    aiger_text = compile_expr_to_aiger(expr)

    assert aiger_text.startswith("aag ")
    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger" in aiger_text


def run_tests():
    test_intersection_a_or_b_star_and_a_star()
    test_intersection_ab_star_and_a_or_b_star()
    test_intersection_disjoint_languages()
    test_intersection_to_aiger_output()

    print("All intersection tests passed.")


if __name__ == "__main__":
    run_tests()
