import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from sequential_regex_compiler import compile_regex_to_sequential  # noqa: E402
from sequential_simulator import simulate  # noqa: E402
from sequential_aiger_writer import SequentialAigerWriter  # noqa: E402


def word_to_trace(word: str) -> list[dict[str, bool]]:
    trace = []

    for ch in word:
        trace.append({
            f"is_{ch}": True,
            "end": False,
        })

    trace.append({
        "end": True,
    })

    return trace


def accepts(pattern: str, word: str) -> bool:
    circuit = compile_regex_to_sequential(pattern)
    outputs = simulate(circuit, word_to_trace(word))
    return outputs[-1]["accept"]


def compile_to_sequential_aiger(pattern: str) -> str:
    circuit = compile_regex_to_sequential(pattern)
    writer = SequentialAigerWriter(circuit)
    return writer.write()


def test_sequential_intersection_a_or_b_star_and_a_star():
    assert accepts("(a|b)*&a*", "") is True
    assert accepts("(a|b)*&a*", "a") is True
    assert accepts("(a|b)*&a*", "aa") is True
    assert accepts("(a|b)*&a*", "aaa") is True

    assert accepts("(a|b)*&a*", "b") is False
    assert accepts("(a|b)*&a*", "ab") is False
    assert accepts("(a|b)*&a*", "ba") is False


def test_sequential_intersection_ab_star_and_a_or_b_star():
    assert accepts("(ab)*&(a|b)*", "") is True
    assert accepts("(ab)*&(a|b)*", "ab") is True
    assert accepts("(ab)*&(a|b)*", "abab") is True
    assert accepts("(ab)*&(a|b)*", "ababab") is True

    assert accepts("(ab)*&(a|b)*", "a") is False
    assert accepts("(ab)*&(a|b)*", "b") is False
    assert accepts("(ab)*&(a|b)*", "aba") is False
    assert accepts("(ab)*&(a|b)*", "abb") is False


def test_sequential_intersection_disjoint_languages():
    assert accepts("a*&b*", "") is True

    assert accepts("a*&b*", "a") is False
    assert accepts("a*&b*", "aa") is False
    assert accepts("a*&b*", "b") is False
    assert accepts("a*&b*", "bb") is False
    assert accepts("a*&b*", "ab") is False
    assert accepts("a*&b*", "ba") is False


def test_sequential_intersection_aiger_has_latches():
    aiger_text = compile_to_sequential_aiger("(a|b)*&a*")
    header = aiger_text.splitlines()[0]

    parts = header.split()

    assert parts[0] == "aag"

    num_latches = int(parts[3])
    assert num_latches > 0

    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger sequential backend" in aiger_text


def run_tests():
    test_sequential_intersection_a_or_b_star_and_a_star()
    test_sequential_intersection_ab_star_and_a_or_b_star()
    test_sequential_intersection_disjoint_languages()
    test_sequential_intersection_aiger_has_latches()

    print("All sequential intersection tests passed.")


if __name__ == "__main__":
    run_tests()
