from parser import parse
from model import build_model
from matcher import matches_or
from compiler import compile_or, compile_exact_string
from evaluator import evaluate
from netlist_builder import NetlistBuilder
from aiger import compile_expr_to_aiger


def test_parser_basic():
    strings = parse("abba | abb")
    assert strings == ["abba", "abb"]


def test_parser_whitespace():
    strings = parse("  abba   |   abb   ")
    assert strings == ["abba", "abb"]


def test_parser_single_string():
    strings = parse("abba")
    assert strings == ["abba"]


def test_parser_invalid_empty_alternative():
    try:
        parse("abba || abb")
        assert False, "Expected ValueError for empty alternative"
    except ValueError:
        pass


def test_model_and_matcher():
    strings = parse("abba | abb")
    model = build_model(strings)

    assert matches_or(model, "abba") is True
    assert matches_or(model, "abb") is True
    assert matches_or(model, "") is False
    assert matches_or(model, "ab") is False
    assert matches_or(model, "abbb") is False
    assert matches_or(model, "abbaa") is False
    assert matches_or(model, "xyz") is False


def test_compile_exact_string():
    strings = parse("abba")
    model = build_model(strings)
    exact_matcher = model.options[0]

    compiled = compile_exact_string(exact_matcher)

    assert evaluate(compiled, "abba") is True
    assert evaluate(compiled, "abb") is False
    assert evaluate(compiled, "abbb") is False
    assert evaluate(compiled, "") is False


def test_compile_or_and_evaluation():
    strings = parse("abba | abb")
    model = build_model(strings)
    compiled = compile_or(model)

    positives = ["abba", "abb"]
    negatives = ["", "ab", "abbb", "abbaa", "xyz"]

    for s in positives:
        assert matches_or(model, s) is True
        assert evaluate(compiled, s) is True

    for s in negatives:
        assert matches_or(model, s) is False
        assert evaluate(compiled, s) is False


def test_netlist_building():
    strings = parse("abba | abb")
    model = build_model(strings)
    compiled = compile_or(model)

    builder = NetlistBuilder()
    output_id = builder.compile_expr(compiled)

    assert output_id in builder.nodes
    assert len(builder.nodes) > 0


def test_aiger_output():
    strings = parse("abba | abb")
    model = build_model(strings)
    compiled = compile_or(model)

    aiger_text = compile_expr_to_aiger(compiled)

    assert aiger_text.startswith("aag ")
    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger" in aiger_text


def run_tests():
    test_parser_basic()
    test_parser_whitespace()
    test_parser_single_string()
    test_parser_invalid_empty_alternative()
    test_model_and_matcher()
    test_compile_exact_string()
    test_compile_or_and_evaluation()
    test_netlist_building()
    test_aiger_output()
    print("All tests passed.")


if __name__ == "__main__":
    run_tests()

# TODO: add tests for future regex operators
