import os
import subprocess
import sys
import tempfile
from unittest import mock

import string_to_aiger.cli as cli_module


ROOT_DIR = os.path.dirname(os.path.dirname(__file__))
OUTPUT_DIR = os.path.join(ROOT_DIR, "outputs")


def run_cli(
    args: list[str],
    entry_point: str = "module",
) -> subprocess.CompletedProcess:
    env = os.environ.copy()
    env.pop("STRING_TO_AIGER_EXTERNAL_AIGER_VALIDATOR", None)

    if entry_point == "console":
        executable_name = (
            "string-to-aiger.exe" if os.name == "nt" else "string-to-aiger"
        )
        command = [os.path.join(os.path.dirname(sys.executable), executable_name)]
    else:
        command = [sys.executable, "-m", "string_to_aiger"]

    return subprocess.run(
        command + args,
        cwd=ROOT_DIR,
        text=True,
        capture_output=True,
        env=env,
    )


def assert_filesystem_error(
    result: subprocess.CompletedProcess,
    operation: str,
    path: str,
) -> None:
    assert result.returncode == 2
    assert result.stdout == ""
    assert f"Unable to {operation} {path!r}" in result.stderr
    assert "Traceback" not in result.stderr


def write_python_script(temp_dir: str, name: str, body: str) -> str:
    path = os.path.join(temp_dir, name)

    with open(path, "w", encoding="utf-8") as f:
        f.write(body)

    return path


def python_command(script_path: str) -> str:
    python_path = sys.executable.replace(os.sep, "/")
    script_path = script_path.replace(os.sep, "/")

    return f'"{python_path}" "{script_path}"'


def test_cli_bounded_backend():
    output_path = os.path.join(OUTPUT_DIR, "test_cli_bounded.aag")

    result = run_cli([
        "--pattern", "(a|b)*&a*",
        "--backend", "bounded",
        "--bound", "4",
        "--output", output_path,
    ])

    assert result.returncode == 0
    assert "Backend: bounded" in result.stdout
    assert "Intersection strategy: structural" in result.stdout
    assert "Length analysis:" in result.stdout
    assert "bound complete: no" in result.stdout
    assert "AIGER validation: passed" in result.stdout
    assert os.path.exists(output_path)

    with open(output_path, "r", encoding="utf-8") as f:
        aiger_text = f.read()

    assert aiger_text.startswith("aag ")
    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger" in aiger_text


def test_cli_sequential_backend():
    output_path = os.path.join(OUTPUT_DIR, "test_cli_sequential.aag")

    result = run_cli([
        "--pattern", "(a|b)*&a*",
        "--backend", "sequential",
        "--output", output_path,
    ])

    assert result.returncode == 0
    assert "Backend: sequential" in result.stdout
    assert "Intersection strategy: structural" in result.stdout
    assert "AIGER validation: passed" in result.stdout
    assert os.path.exists(output_path)

    with open(output_path, "r", encoding="utf-8") as f:
        aiger_text = f.read()

    assert aiger_text.startswith("aag ")
    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger sequential backend" in aiger_text

    header = aiger_text.splitlines()[0]
    parts = header.split()

    assert parts[0] == "aag"

    num_latches = int(parts[3])
    assert num_latches > 0


def test_cli_bounded_product_intersection_strategy():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "bounded_product.aag")

        result = run_cli([
            "--pattern", "(a|b)*&a*",
            "--backend", "bounded",
            "--intersection-strategy", "product",
            "--bound", "4",
            "--output", output_path,
        ])

        assert result.returncode == 0
        assert "Backend: bounded" in result.stdout
        assert "Intersection strategy: product" in result.stdout
        assert "Length analysis:" in result.stdout
        assert "AIGER validation: passed" in result.stdout
        assert os.path.exists(output_path)

        with open(output_path, "r", encoding="utf-8") as f:
            aiger_text = f.read()

        assert aiger_text.startswith("aag ")
        assert "o0 accept" in aiger_text
        assert "generated by string-to-aiger" in aiger_text


def test_cli_sequential_product_intersection_strategy():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "sequential_product.aag")

        result = run_cli([
            "--pattern", "(a|b)*&a*",
            "--backend", "sequential",
            "--intersection-strategy", "product",
            "--output", output_path,
        ])

        assert result.returncode == 0
        assert "Backend: sequential" in result.stdout
        assert "Intersection strategy: product" in result.stdout
        assert "AIGER validation: passed" in result.stdout
        assert os.path.exists(output_path)

        with open(output_path, "r", encoding="utf-8") as f:
            aiger_text = f.read()

        assert aiger_text.startswith("aag ")
        assert "o0 accept" in aiger_text
        assert "generated by string-to-aiger sequential backend" in aiger_text

        header = aiger_text.splitlines()[0]
        parts = header.split()

        assert parts[0] == "aag"

        num_latches = int(parts[3])
        assert num_latches > 0


def test_cli_rejects_invalid_intersection_strategy():
    result = run_cli([
        "--pattern", "(a|b)*&a*",
        "--backend", "bounded",
        "--intersection-strategy", "invalid",
    ])

    assert result.returncode != 0
    assert "invalid choice" in result.stderr


def test_cli_input_file_backend():
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "pattern.txt")
        output_path = os.path.join(temp_dir, "from_file.aag")

        with open(input_path, "w", encoding="utf-8") as f:
            f.write("(a|b)*&a*")

        result = run_cli([
            "--input-file", input_path,
            "--backend", "bounded",
            "--bound", "4",
            "--output", output_path,
        ])

        assert result.returncode == 0
        assert "Backend: bounded" in result.stdout
        assert "Intersection strategy: structural" in result.stdout
        assert "Length analysis:" in result.stdout
        assert "bound complete: no" in result.stdout
        assert "AIGER validation: passed" in result.stdout
        assert os.path.exists(output_path)

        with open(output_path, "r", encoding="utf-8") as f:
            aiger_text = f.read()

        assert aiger_text.startswith("aag ")
        assert "o0 accept" in aiger_text
        assert "generated by string-to-aiger" in aiger_text


def test_cli_input_file_product_strategy():
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "pattern.txt")
        output_path = os.path.join(temp_dir, "from_file_product.aag")

        with open(input_path, "w", encoding="utf-8") as f:
            f.write("(a|b)*&a*")

        result = run_cli([
            "--input-file", input_path,
            "--backend", "bounded",
            "--intersection-strategy", "product",
            "--bound", "4",
            "--output", output_path,
        ])

        assert result.returncode == 0
        assert "Backend: bounded" in result.stdout
        assert "Intersection strategy: product" in result.stdout
        assert "Length analysis:" in result.stdout
        assert "AIGER validation: passed" in result.stdout
        assert os.path.exists(output_path)

        with open(output_path, "r", encoding="utf-8") as f:
            aiger_text = f.read()

        assert aiger_text.startswith("aag ")
        assert "o0 accept" in aiger_text
        assert "generated by string-to-aiger" in aiger_text


def test_cli_reports_complete_bound_for_finite_pattern():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "finite.aag")

        result = run_cli([
            "--pattern", "a{1,3}",
            "--backend", "bounded",
            "--bound", "3",
            "--output", output_path,
        ])

        assert result.returncode == 0
        assert "Length analysis:" in result.stdout
        assert "min length: 1" in result.stdout
        assert "max length: 3" in result.stdout
        assert "exact: yes" in result.stdout
        assert "bound complete: yes" in result.stdout
        assert "AIGER validation: passed" in result.stdout
        assert os.path.exists(output_path)


def test_cli_reports_incomplete_bound_for_finite_pattern():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "finite_incomplete.aag")

        result = run_cli([
            "--pattern", "a{1,3}",
            "--backend", "bounded",
            "--bound", "2",
            "--output", output_path,
        ])

        assert result.returncode == 0
        assert "Length analysis:" in result.stdout
        assert "min length: 1" in result.stdout
        assert "max length: 3" in result.stdout
        assert "exact: yes" in result.stdout
        assert "bound complete: no" in result.stdout
        assert "AIGER validation: passed" in result.stdout
        assert os.path.exists(output_path)


def test_cli_skip_validation():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "skip_validation.aag")

        result = run_cli([
            "--pattern", "(a|b)*&a*",
            "--backend", "bounded",
            "--bound", "4",
            "--output", output_path,
            "--skip-validation",
        ])

        assert result.returncode == 0
        assert "Intersection strategy: structural" in result.stdout
        assert "AIGER validation: skipped" in result.stdout
        assert os.path.exists(output_path)

        with open(output_path, "r", encoding="utf-8") as f:
            aiger_text = f.read()

        assert aiger_text.startswith("aag ")
        assert "o0 accept" in aiger_text


def test_cli_external_validation_skips_without_command():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "external_skipped.aag")

        result = run_cli([
            "--pattern", "a*",
            "--backend", "bounded",
            "--bound", "3",
            "--output", output_path,
            "--external-validation",
        ])

        assert result.returncode == 0
        assert "AIGER validation: passed" in result.stdout
        assert "External AIGER validation: skipped" in result.stdout
        assert "No external AIGER validator command configured." in result.stdout
        assert os.path.exists(output_path)


def test_cli_external_validation_passes_with_command():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "external_passed.aag")

        script_path = write_python_script(
            temp_dir,
            "external_pass_validator.py",
            "\n".join([
                "import sys",
                "with open(sys.argv[1], 'r', encoding='utf-8') as f:",
                "    text = f.read()",
                "assert text.startswith('aag ')",
                "raise SystemExit(0)",
            ]),
        )

        result = run_cli([
            "--pattern", "a*",
            "--backend", "bounded",
            "--bound", "3",
            "--output", output_path,
            "--external-validation",
            "--external-validator-command", python_command(script_path),
        ])

        assert result.returncode == 0
        assert "AIGER validation: passed" in result.stdout
        assert "External AIGER validation: passed" in result.stdout
        assert "External AIGER validation passed." in result.stdout
        assert os.path.exists(output_path)


def test_cli_external_validator_command_implies_external_validation():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "external_command_implied.aag")

        script_path = write_python_script(
            temp_dir,
            "external_implied_validator.py",
            "\n".join([
                "import sys",
                "with open(sys.argv[1], 'r', encoding='utf-8') as f:",
                "    text = f.read()",
                "assert text.startswith('aag ')",
                "raise SystemExit(0)",
            ]),
        )

        result = run_cli([
            "--pattern", "a*",
            "--backend", "bounded",
            "--bound", "3",
            "--output", output_path,
            "--external-validator-command", python_command(script_path),
        ])

        assert result.returncode == 0
        assert "External AIGER validation: passed" in result.stdout
        assert os.path.exists(output_path)


def test_cli_external_validation_fails_with_failing_command():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = os.path.join(temp_dir, "external_failed.aag")

        script_path = write_python_script(
            temp_dir,
            "external_fail_validator.py",
            "\n".join([
                "raise SystemExit(7)",
            ]),
        )

        result = run_cli([
            "--pattern", "a*",
            "--backend", "bounded",
            "--bound", "3",
            "--output", output_path,
            "--external-validation",
            "--external-validator-command", python_command(script_path),
        ])

        assert result.returncode != 0
        assert "External AIGER validation failed." in result.stderr
        assert os.path.exists(output_path)


def test_cli_reports_input_and_output_file_errors():
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "empty.txt")
        output_path = os.path.join(temp_dir, "empty.aag")

        with open(input_path, "w", encoding="utf-8") as f:
            f.write("")

        result = run_cli([
            "--input-file", input_path,
            "--backend", "bounded",
            "--bound", "4",
            "--output", output_path,
        ])

        assert result.returncode != 0
        assert "Input file is empty" in result.stderr

        missing_path = os.path.join(temp_dir, "missing.txt")
        missing_args = [
            "--input-file", missing_path,
            "--output", output_path,
        ]
        module_result = run_cli(missing_args)
        console_result = run_cli(missing_args, entry_point="console")

        assert_filesystem_error(module_result, "read input file", missing_path)
        assert console_result.returncode == module_result.returncode
        assert console_result.stdout == module_result.stdout
        assert console_result.stderr == module_result.stderr

        input_directory = os.path.join(temp_dir, "input_directory")
        os.makedirs(input_directory)
        result = run_cli([
            "--input-file", input_directory,
            "--output", output_path,
        ])
        assert_filesystem_error(result, "read input file", input_directory)

        output_directory = os.path.join(temp_dir, "output_directory")
        os.makedirs(output_directory)
        result = run_cli([
            "--pattern", "a",
            "--output", output_directory,
        ])
        assert_filesystem_error(result, "write output file", output_directory)

        parent_file = os.path.join(temp_dir, "parent_file")
        with open(parent_file, "w", encoding="utf-8") as f:
            f.write("not a directory")

        blocked_output = os.path.join(parent_file, "child.aag")
        result = run_cli([
            "--pattern", "a",
            "--output", blocked_output,
        ])
        assert_filesystem_error(result, "write output file", blocked_output)

    unexpected_error = OSError("unexpected compiler failure")
    with (
        mock.patch.object(
            sys,
            "argv",
            ["string-to-aiger", "--pattern", "a"],
        ),
        mock.patch.object(
            cli_module,
            "compile_bounded",
            side_effect=unexpected_error,
        ),
    ):
        try:
            cli_module.main()
        except OSError as error:
            assert error is unexpected_error
        else:
            raise AssertionError("Unexpected compiler OSError was suppressed")


def test_cli_requires_pattern_or_input_file():
    result = run_cli([])

    assert result.returncode != 0
    assert "one of the arguments --pattern --input-file is required" in result.stderr


def test_cli_rejects_pattern_and_input_file_together():
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "pattern.txt")

        with open(input_path, "w", encoding="utf-8") as f:
            f.write("a*")

        result = run_cli([
            "--pattern", "a*",
            "--input-file", input_path,
            "--backend", "bounded",
        ])

        assert result.returncode != 0
        assert "not allowed with argument" in result.stderr


def run_tests():
    test_cli_bounded_backend()
    test_cli_sequential_backend()
    test_cli_bounded_product_intersection_strategy()
    test_cli_sequential_product_intersection_strategy()
    test_cli_rejects_invalid_intersection_strategy()
    test_cli_input_file_backend()
    test_cli_input_file_product_strategy()
    test_cli_reports_complete_bound_for_finite_pattern()
    test_cli_reports_incomplete_bound_for_finite_pattern()
    test_cli_skip_validation()
    test_cli_external_validation_skips_without_command()
    test_cli_external_validation_passes_with_command()
    test_cli_external_validator_command_implies_external_validation()
    test_cli_external_validation_fails_with_failing_command()
    test_cli_reports_input_and_output_file_errors()
    test_cli_requires_pattern_or_input_file()
    test_cli_rejects_pattern_and_input_file_together()

    print("All CLI tests passed.")


if __name__ == "__main__":
    run_tests()
