import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(__file__))
sys.path.append(ROOT_DIR)

from string_to_aiger.bounded.product_bounded_compiler import compile_regex_bounded_product  # noqa: E402
from string_to_aiger.logic.evaluator import evaluate  # noqa: E402
from string_to_aiger.sequential.product_sequential_compiler import compile_regex_to_sequential_product  # noqa: E402
from string_to_aiger.sequential.sequential_simulator import simulate  # noqa: E402
from string_to_aiger.sequential.sequential_aiger_writer import SequentialAigerWriter  # noqa: E402


def word_to_trace(word: str) -> list[dict[str, bool]]:
    trace = []

    for ch in word:
        trace.append({
            f"is_{ch}": True,
            "end": False,
        })

    trace.append({
        "end": True,
    })

    return trace


def product_bounded_accepts(pattern: str, bound: int, word: str) -> bool:
    expr = compile_regex_bounded_product(pattern, bound)
    return evaluate(expr, word)


def product_sequential_accepts(pattern: str, word: str) -> bool:
    circuit = compile_regex_to_sequential_product(pattern)
    outputs = simulate(circuit, word_to_trace(word))
    return outputs[-1]["accept"]


def test_product_bounded_a_or_b_star_and_a_star():
    pattern = "(a|b)*&a*"
    bound = 4

    assert product_bounded_accepts(pattern, bound, "") is True
    assert product_bounded_accepts(pattern, bound, "a") is True
    assert product_bounded_accepts(pattern, bound, "aa") is True
    assert product_bounded_accepts(pattern, bound, "aaa") is True
    assert product_bounded_accepts(pattern, bound, "aaaa") is True

    assert product_bounded_accepts(pattern, bound, "b") is False
    assert product_bounded_accepts(pattern, bound, "ab") is False
    assert product_bounded_accepts(pattern, bound, "ba") is False

    # Rejected because the bounded backend only accepts up to the configured bound.
    assert product_bounded_accepts(pattern, bound, "aaaaa") is False


def test_product_sequential_a_or_b_star_and_a_star():
    pattern = "(a|b)*&a*"

    assert product_sequential_accepts(pattern, "") is True
    assert product_sequential_accepts(pattern, "a") is True
    assert product_sequential_accepts(pattern, "aa") is True
    assert product_sequential_accepts(pattern, "aaa") is True
    assert product_sequential_accepts(pattern, "aaaa") is True

    assert product_sequential_accepts(pattern, "b") is False
    assert product_sequential_accepts(pattern, "ab") is False
    assert product_sequential_accepts(pattern, "ba") is False


def test_product_bounded_ab_star_and_a_or_b_star():
    pattern = "(ab)*&(a|b)*"
    bound = 6

    assert product_bounded_accepts(pattern, bound, "") is True
    assert product_bounded_accepts(pattern, bound, "ab") is True
    assert product_bounded_accepts(pattern, bound, "abab") is True
    assert product_bounded_accepts(pattern, bound, "ababab") is True

    assert product_bounded_accepts(pattern, bound, "a") is False
    assert product_bounded_accepts(pattern, bound, "b") is False
    assert product_bounded_accepts(pattern, bound, "aba") is False
    assert product_bounded_accepts(pattern, bound, "abb") is False


def test_product_sequential_disjoint_languages():
    pattern = "a*&b*"

    assert product_sequential_accepts(pattern, "") is True

    assert product_sequential_accepts(pattern, "a") is False
    assert product_sequential_accepts(pattern, "aa") is False
    assert product_sequential_accepts(pattern, "b") is False
    assert product_sequential_accepts(pattern, "bb") is False
    assert product_sequential_accepts(pattern, "ab") is False
    assert product_sequential_accepts(pattern, "ba") is False


def test_product_sequential_aiger_has_latches():
    circuit = compile_regex_to_sequential_product("(a|b)*&a*")
    writer = SequentialAigerWriter(circuit)
    aiger_text = writer.write()

    header = aiger_text.splitlines()[0]
    parts = header.split()

    assert parts[0] == "aag"

    num_latches = int(parts[3])
    assert num_latches > 0

    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger sequential backend" in aiger_text


def run_tests():
    test_product_bounded_a_or_b_star_and_a_star()
    test_product_sequential_a_or_b_star_and_a_star()
    test_product_bounded_ab_star_and_a_or_b_star()
    test_product_sequential_disjoint_languages()
    test_product_sequential_aiger_has_latches()

    print("All product backend tests passed.")


if __name__ == "__main__":
    run_tests()
