import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(__file__))
sys.path.append(ROOT_DIR)

from string_to_aiger.regex.regex_parser import parse_regex  # noqa: E402
from string_to_aiger.nfa.nfa_builder import build_nfa  # noqa: E402
from string_to_aiger.sequential.nfa_to_sequential import compile_nfa_to_sequential  # noqa: E402
from string_to_aiger.sequential.sequential_simulator import simulate  # noqa: E402
from string_to_aiger.sequential.sequential_aiger_writer import SequentialAigerWriter  # noqa: E402


def word_to_trace(word: str) -> list[dict[str, bool]]:
    trace = []

    for ch in word:
        trace.append({
            f"is_{ch}": True,
            "end": False,
        })

    trace.append({
        "end": True,
    })

    return trace


def accepts(pattern: str, word: str) -> bool:
    ast = parse_regex(pattern)
    nfa = build_nfa(ast)
    circuit = compile_nfa_to_sequential(nfa)

    outputs = simulate(circuit, word_to_trace(word))
    return outputs[-1]["accept"]


def compile_to_sequential_aiger(pattern: str) -> str:
    ast = parse_regex(pattern)
    nfa = build_nfa(ast)
    circuit = compile_nfa_to_sequential(nfa)

    writer = SequentialAigerWriter(circuit)
    return writer.write()


def test_sequential_a_star():
    assert accepts("a*", "") is True
    assert accepts("a*", "a") is True
    assert accepts("a*", "aa") is True
    assert accepts("a*", "aaa") is True

    assert accepts("a*", "b") is False
    assert accepts("a*", "ab") is False
    assert accepts("a*", "ba") is False


def test_sequential_ab_star():
    assert accepts("(ab)*", "") is True
    assert accepts("(ab)*", "ab") is True
    assert accepts("(ab)*", "abab") is True
    assert accepts("(ab)*", "ababab") is True

    assert accepts("(ab)*", "a") is False
    assert accepts("(ab)*", "abb") is False
    assert accepts("(ab)*", "aba") is False


def test_sequential_a_or_b_star():
    assert accepts("(a|b)*", "") is True
    assert accepts("(a|b)*", "a") is True
    assert accepts("(a|b)*", "b") is True
    assert accepts("(a|b)*", "ab") is True
    assert accepts("(a|b)*", "ba") is True
    assert accepts("(a|b)*", "abba") is True

    assert accepts("(a|b)*", "abc") is False


def test_sequential_aiger_has_latches():
    aiger_text = compile_to_sequential_aiger("a*")
    header = aiger_text.splitlines()[0]

    parts = header.split()
    assert parts[0] == "aag"

    num_latches = int(parts[3])
    assert num_latches > 0

    assert "o0 accept" in aiger_text
    assert "generated by string-to-aiger sequential backend" in aiger_text


def run_tests():
    test_sequential_a_star()
    test_sequential_ab_star()
    test_sequential_a_or_b_star()
    test_sequential_aiger_has_latches()

    print("All sequential tests passed.")


if __name__ == "__main__":
    run_tests()
