from collections.abc import Mapping
from string_to_aiger.netlist.netlist import Input, Const, AndGate, OrGate, Node


# This class serializes a boolean netlist into ASCII AIGER format by assigning
# literals to inputs and logic gates and recursively compiling the circuit graph.

class AigerWriter:
    def __init__(self, nodes: Mapping[int, Node], output_node: int):
        self.nodes = nodes
        self.output_node = output_node

        self.input_literals: dict[int, int] = {}
        self.and_literals: dict[int, int] = {}

        self.inputs: list[tuple[int, str]] = []
        self.ands: list[tuple[int, int, int]] = []

        self.next_var = 1

    def new_literal(self) -> int:
        lit = 2 * self.next_var
        self.next_var += 1
        return lit

    def invert(self, lit: int) -> int:
        return lit ^ 1

    def compile_node(self, node_id: int) -> int:
        if node_id in self.input_literals:
            return self.input_literals[node_id]

        if node_id in self.and_literals:
            return self.and_literals[node_id]

        node = self.nodes[node_id]

        if isinstance(node, Input):
            lit = self.new_literal()
            self.input_literals[node_id] = lit
            self.inputs.append((lit, node.name))
            return lit

        if isinstance(node, Const):
            # AIGER constant false = 0, true = 1
            return 1 if node.value else 0

        if isinstance(node, AndGate):
            left_lit = self.compile_node(node.left)
            right_lit = self.compile_node(node.right)

            out_lit = self.new_literal()
            self.and_literals[node_id] = out_lit
            self.ands.append((out_lit, left_lit, right_lit))
            return out_lit

        if isinstance(node, OrGate):
            # a OR b = ~(~a AND ~b)
            left_lit = self.compile_node(node.left)
            right_lit = self.compile_node(node.right)

            neg_left = self.invert(left_lit)
            neg_right = self.invert(right_lit)

            and_lit = self.new_literal()
            self.and_literals[node_id] = and_lit
            self.ands.append((and_lit, neg_left, neg_right))

            return self.invert(and_lit)

        raise TypeError(f"Unknown node type: {type(node)}")

    def write(self) -> str:
        """Serialize the compiled netlist into ASCII AIGER format."""
        output_lit = self.compile_node(self.output_node)

        num_inputs = len(self.inputs)
        num_latches = 0
        num_outputs = 1
        num_ands = len(self.ands)

        # TODO: validate AIGER limits for large instances
        max_variable_index = self.next_var - 1

        lines = [
            f"aag {max_variable_index} {num_inputs} "
            f"{num_latches} {num_outputs} {num_ands}"
        ]

        # input literals
        for lit, _name in self.inputs:
            lines.append(str(lit))

        # outputs
        lines.append(str(output_lit))

        # and gates
        for lhs, rhs0, rhs1 in self.ands:
            lines.append(f"{lhs} {rhs0} {rhs1}")

        # symbolic names
        for i, (_lit, name) in enumerate(self.inputs):
            lines.append(f"i{i} {name}")

        lines.append("o0 accept")
        lines.append("c")
        lines.append("generated by string-to-aiger")

        return "\n".join(lines)
